[CSL-2125] Bump up universum to 1.1.0
input-output-hk/cardano-report-server pull request #16
Opened 2018-02-21 15:41 UTC by ChShersh

This is needed for CSL-2125 (revers `foldl'` change and introduce more refactorings and improvements).

2018-02-21 17:44 UTC, gromakovsky approved these changes

2018-02-21 19:43 UTC, ChShersh commented
Maybe it's not a good idea to merge this PR yet because it has lower bound for `universum >= 1.1.0`. Some problems may happen before we migrate to GHC-8.2.2 and after we want something else from `report-server`.

2018-02-26 10:59 UTC, volhovm requested changes
Must wait for a while.

2018-02-26 10:59 UTC, volhovm commented on cardano-report-server.cabal
> +                     , universum >= 1.1.0
We need it to be `>= 0.9.0` since CSL release uses it.

2018-09-02 06:25 UTC, closed without merging